version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/Spring_Boot_DB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    networks:
      - scamazone-network
    depends_on:
      - mysqldb

  mysqldb:
    image: bitnami/mysql
    networks:
      - scamazone-network
    environment:
      - MYSQL_ROOT_PASSWORD=Abdur-Rahman05
      - MYSQL_DATABASE=Spring_Boot_DB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Abdur-Rahman05

networks:
  scamazone-network:
    driver: bridge